name: pre-commit

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - development

  pull_request:
    branches:
      - main
      - development

env:
  package-name: "rl_exercises"

jobs:
  run-all-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.14"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install SWIG
        run: |
          sudo apt-get update
          sudo apt-get install --yes swig

      - name: Install locked dependencies
        run: uv sync --extra dev --frozen

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

      - name: Run final-project tests
        run: uv run pytest tests/final_project -q